<a href="https://colab.research.google.com/github/IbrahimSayyad2001/dataset/blob/main/ipl2024scheduledataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [48]:
d = {
    "Match No": list(range(1, 22)),
    "Day": ["Fri", "Sat", "Sat", "Sun", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", "Sun"],
    "Date": ["22-03-2024", "23-03-2024", "23-03-2024", "24-03-2024", "24-03-2024", "25-03-2024", "26-03-2024", "27-03-2024", "28-03-2024", "29-03-2024", "30-03-2024", "31-03-2024", "31-03-2024", "01-04-2024", "02-04-2024", "03-04-2024", "04-04-2024", "05-04-2024", "06-04-2024", "07-04-2024", "07-04-2024"],
    "Match": ["CSK vs RCB", "PBKS vs DC", "KKR vs SRH", "RR vs LSG", "GT vs MI", "RCB vs PBKS", "CSK vs GT", "SRH vs MI", "RR vs DC", "RCB vs KKR", "LSG vs PBKS", "GT vs SRH", "DC vs CSK", "MI vs RR", "RCB vs LSG", "DC vs KKR", "GT vs PBKS", "SRH vs CSK", "RR vs RCB", "MI vs DC", "LSG vs GT"],
    "Time (IST)": ["8:00 PM", "3:30 PM", "7:30 PM", "3:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "3:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "7:30 PM", "3:30 PM", "7:30 PM"],
    "Venue": ["Chennai", "Mohali", "Kolkata", "Jaipur", "Ahmedabad", "Bengaluru", "Chennai", "Hyderabad", "Jaipur", "Bengaluru", "Lucknow", "Ahmedabad", "Visakhapatnam", "Mumbai", "Bengaluru", "Visakhapatnam", "Ahmedabad", "Hyderabad", "Jaipur", "Mumbai", "Lucknow"],
}

In [96]:
df=pd.DataFrame(d)

In [95]:
np.random.seed(0)
adult_ticket_rate = np.random.randint(1200, 3001,size=len(df))
num_adult_tickets = np.random.randint(1, 2000, size=len(df))
senior_ticket_rate = np.random.randint(800, 1501,size=len(df))
num_senior_tickets = np.random.randint(0, 50, size=len(df))
child_ticket_rate = np.random.randint(500, 1001,size=len(df))
num_child_tickets = np.random.randint(0, 200, size=len(df))
vip_ticket_rate = np.random.randint(5000, 10001, size=len(df))
num_vip_ticket = np.random.randint(0,300 ,size=len(df))
corporate_ticket_rate = np.random.randint(4000, 8001, size=len(df))
num_corporate_ticket=np.random.randint(0,250,size=len(df))
student_ticket_rate = np.random.randint(700, 2501, size=len(df))
num_student_ticket=np.random.randint(0,400,size=len(df))

#np.random.seed(42)

In [97]:
df['Adult Ticket Rate'] = adult_ticket_rate
df['Number of Adult Tickets'] = num_adult_tickets

df['Senior Ticket Rate'] = senior_ticket_rate
df['Number of Senior Tickets'] = num_senior_tickets

df['Child Ticket Rate'] = child_ticket_rate
df['Number of Child Tickets'] = num_child_tickets

df['VIP Ticket Rate'] = vip_ticket_rate
df['Number of Vip Tickets'] = num_vip_ticket

df['Corporate Ticket Rate'] = corporate_ticket_rate
df['Number of Corporate Tickets'] = num_corporate_ticket

df['Student Ticket Rate'] = student_ticket_rate
df['Number of Student Tickets'] = num_student_ticket

In [104]:
df["Total_number_of_tickets_sell"]=(df['Number of Adult Tickets']+df['Number of Senior Tickets'] +df['Number of Child Tickets']+df['Number of Vip Tickets']+df['Number of Corporate Tickets']+df['Number of Student Tickets'])

In [101]:
df.columns

Index(['Match No', 'Day', 'Date', 'Match', 'Time (IST)', 'Venue',
       'Adult Ticket Rate', 'Number of Adult Tickets', 'Senior Ticket Rate',
       'Number of Senior Tickets', 'Child Ticket Rate',
       'Number of Child Tickets', 'VIP Ticket Rate', 'Number of Vip Tickets',
       'Corporate Ticket Rate', 'Number of Corporate Tickets',
       'Student Ticket Rate', 'Number of Student Tickets'],
      dtype='object')

In [103]:
df

,Match No,Day,Date,Match,Time (IST),Venue,Adult Ticket Rate,Number of Adult Tickets,Senior Ticket Rate,Number of Senior Tickets,Child Ticket Rate,Number of Child Tickets,VIP Ticket Rate,Number of Vip Tickets,Corporate Ticket Rate,Number of Corporate Tickets,Student Ticket Rate,Number of Student Tickets,Total number of ticket sell
0,1,Fri,22-03-2024,CSK vs RCB,8:00 PM,Chennai,1884,88,1459,17,584,117,5973,174,5020,104,1853,104,604
1,2,Sat,23-03-2024,PBKS vs DC,3:30 PM,Mohali,1759,175,947,15,703,85,9464,42,6646,160,1435,212,689
2,3,Sat,23-03-2024,KKR vs SRH,7:30 PM,Kolkata,2853,1625,1223,4,824,48,7023,184,7533,228,1512,138,2227
3,4,Sun,24-03-2024,RR vs LSG,3:30 PM,Jaipur,2416,850,1088,41,762,49,7965,77,6937,121,916,182,1320
4,5,Sun,24-03-2024,GT vs MI,7:30 PM,Ahmedabad,2035,1702,1065,42,952,69,5201,286,5645,70,2105,125,2294
5,6,Mon,25-03-2024,RCB vs PBKS,7:30 PM,Bengaluru,1963,538,1497,31,547,169,7431,280,4843,213,724,156,1387
6,7,Tue,26-03-2024,CSK vs GT,7:30 PM,Chennai,2931,846,1439,1,627,163,7418,125,6744,31,767,111,1277
7,8,Wed,27-03-2024,SRH vs MI,7:30 PM,Hyderabad,2583,73,1344,1,1000,192,9651,258,5552,13,1678,258,795
8,9,Thu,28-03-2024,RR vs DC,7:30 PM,Jaipur,2233,778,1343,39,631,95,8455,3,7224,71,1707,27,1013
9,10,Fri,29-03-2024,RCB vs KKR,7:30 PM,Bengaluru,2947,1941,1044,41,960,197,9226,94,4925,184,2495,217,2674
10,11,Sat,30-03-2024,LSG vs PBKS,7:30 PM,Lucknow,1477,116,951,35,856,94,5931,226,6197,152,934,151,774
11,12,Sun,31-03-2024,GT vs SRH,3:30 PM,Ahmedabad,2978,977,1475,38,680,0,6987,269,5134,79,2440,309,1672
12,13,Sun,31-03-2024,DC vs CSK,7:30 PM,Visakhapatnam,1799,756,1310,11,988,113,7787,296,4025,41,991,307,1524
13,14,Mon,01-04-2024,MI vs RR,7:30 PM,Mumbai,2294,1734,1259,46,834,178,9305,19,5488,18,2450,174,2169
14,15,Tue,02-04-2024,RCB vs LSG,7:30 PM,Bengaluru,2696,1872,983,18,643,36,7610,95,4956,40,1722,148,2209
15,16,Wed,03-04-2024,DC vs KKR,7:30 PM,Visakhapatnam,1800,1456,828,27,648,162,9182,248,5913,182,1401,29,2104
16,17,Thu,04-04-2024,GT vs PBKS,7:30 PM,Ahmedabad,2620,449,928,0,727,48,9968,180,6934,207,2433,67,951
17,18,Fri,05-04-2024,SRH vs CSK,7:30 PM,Hyderabad,1514,851,928,14,942,93,7059,270,5141,11,1427,35,1274
18,19,Sat,06-04-2024,RR vs RCB,7:30 PM,Jaipur,1905,100,853,35,779,131,5307,260,5469,166,1255,295,987
19,20,Sun,07-04-2024,MI vs DC,3:30 PM,Mumbai,2710,1202,1350,12,707,98,6152,237,5619,111,732,393,2053
20,21,Sun,07-04-2024,LSG vs GT,7:30 PM,Lucknow,1751,756,1288,42,897,42,5275,139,6721,93,1735,73,1145

In [106]:
df.to_csv('IPL schedule for 2024 ')